name: Run Face Detection

on: [push]

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install numpy opencv-python matplotlib scikit-learn scipy wandb

      - name: Run face detection script
        run: python script.py

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: output-images
          path: |
            template_faces.jpg
            detected_faces.jpg
            face_clustering.png
            face_clustering_centroids.png
            face_clustering_template.png
            face_clustering_template_point.png
